name: SoSpec
version: 1.1
author: somax
main: so.max1soft.spec.Main
description: Читеры???
commands:
  spec:
    description: spec
    usage: /spec
  permissions:
    spec.moder:
      description: Permission to use /spec command
      default: op

